<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="examsRepository" nsURI="http://www.example.org/examsRepository"
    nsPrefix="examsRepository">
  <eClassifiers xsi:type="ecore:EClass" name="Alternative">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alternativeStatement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theme" eType="#//Theme"
        defaultValueLiteral="other"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" lowerBound="2"
        upperBound="-1" eType="#//Alternative" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questions" upperBound="-1"
        eType="#//Question" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" lowerBound="1"
        upperBound="-1" eType="#//Question" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExamSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//Repository"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exam" upperBound="-1" eType="#//Exam"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Theme">
    <eLiterals name="softwarePatterns" literal="Software Patterns"/>
    <eLiterals name="frameworks" value="1" literal="Frameworks"/>
    <eLiterals name="softwareComponents" value="2" literal="Software Components"/>
    <eLiterals name="softwareProductLine" value="3" literal="Software Product Line"/>
    <eLiterals name="SOA" value="4" literal="Serviceoriented Architecture"/>
    <eLiterals name="SoS" value="5" literal="Systems of Systems"/>
    <eLiterals name="MDE" value="6" literal="Model driven Engineering"/>
    <eLiterals name="other" value="7" literal="other"/>
  </eClassifiers>
</ecore:EPackage>
